### ISSUE TITLE
Bug with minimize function while unpined on IE11

### ISSUE THREAD

**Issue by Aeryax** [arboshiki/lobipanel#22]
Hi,

When I try to minimize two or more unpined panels on IE11, these are stacking on the bottom left corner.
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/10158198/18906067/50f2cc12-8566-11e6-99d9-790e8c6b2c72.png)

It is working well on FF/Chrome. Do you think it is possible to fix it ?

Thanks for your work.

**Comment by arboshiki** [comment]
Thanks for creating issue.

try to add the following css to your project
```css
.lobipanel.panel-unpin.panel-minimized > .panel-heading .dropdown .dropdown-menu{
  min-width: 0;
}

.lobipanel.panel-unpin.panel-minimized{
  position: static;
}
```

This is because IE does not have `position: initial` or `min-width: initial`.

Let me know if this helps
